apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: lighthouse-hmac-token
    properties:
    - name: token
      question: Lighthouse webhook token
      help: The webhook token is used as a secret to verify webhooks come from a trusted
        source
      generator: hmac
  - name: lighthouse-oauth-token
    properties:
    - name: token
      question: Lighthouse webhook token
      help: The webhook token is used as a secret to verify webhooks come from a trusted
        source
      generator: gitOperator.password
  - name: knative-git-user-pass
    properties:
    - name: username
      key: secret/data/jx/pipelineUser
      question: the pipeline username
      help: the user name used by pipelines running in Jenkins X
      generator: gitOperator.username
    - name: token
      key: secret/data/jx/pipelineUser
      question: the pipeline token or password
      help: the token or password used by pipelines running in Jenkins X
      generator: gitOperator.password
  - name: jenkins-x-bucketrepo
    properties:
    - name: username
      question: bucket repository user name
      help: The username used to authenticate with the bucket repository
      defaultValue: admin
    - name: password
      question: bucket repository password
      help: The password to authenticate with the bucket repository
      minLength: 5
      maxLength: 41
      generator: password
  - name: jenkins-x-chartmuseum
    properties:
    - name: username
      question: chartmuseum repository user name
      help: The username used to authenticate with chartmuseum (the helm repository)
      defaultValue: admin
    - name: password
      question: chartmuseum repository password
      help: The password to authenticate with the chartmuseum (the helm repository)
      minLength: 5
      maxLength: 41
      generator: password
  - name: nexus
    properties:
    - name: username
      question: nexus user name
      help: The username used to authenticate with nexus
      defaultValue: admin
    - name: password
      question: nexus password
      help: The password to authenticate with nexus
      minLength: 5
      maxLength: 41
      defaultValue: admin123
  - name: knative-docker-user-pass
    properties:
    - name: username
      question: Docker Registry username
      help: The username used to access the external docker registry
      defaultValue: admin
    - name: password
      question: Docker Registry password
      help: The password used to access the external docker registry
      generator: password
  - name: jenkins-maven-settings
    properties:
    - name: settingsXml
      question: Maven settings XML contents
      help: This is the maven settings XML which is mounted for Java builds
      defaultValue: |-
        <settings>
            <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
            <localRepository>${user.home}/.mvnrepository</localRepository>
            <!-- lets disable the download progress indicator that fills up logs -->
            <interactiveMode>false</interactiveMode>
            <mirrors>
                <mirror>
                <id>nexus</id>
                <mirrorOf>external:*</mirrorOf>
                <url>http://nexus:8081/repository/maven-group/</url>
                </mirror>
            </mirrors>
            <servers>
                <server>
                <id>nexus</id>
                <username>admin</username>
                <password>admin123</password>
            </server>
            <server>
                <id>oss-sonatype-staging</id>
                <username></username>
                <password></password>
                </server>
            </servers>
            <profiles>
                <profile>
                    <id>nexus</id>
                    <properties>
                        <altDeploymentRepository>nexus::default::http://nexus/repository/maven-snapshots/</altDeploymentRepository>
                        <altReleaseDeploymentRepository>nexus::default::http://nexus/repository/maven-releases/</altReleaseDeploymentRepository>
                        <altSnapshotDeploymentRepository>nexus::default::http://nexus/repository/maven-snapshots/</altSnapshotDeploymentRepository>
                    </properties>
                </profile>
                <profile>
                    <id>release</id>
                    <properties>
                        <gpg.executable>gpg</gpg.executable>
                        <gpg.passphrase>mysecretpassphrase</gpg.passphrase>
                    </properties>
                </profile>
            </profiles>
            <activeProfiles>
                <!--make the profile active all the time -->
                <activeProfile>nexus</activeProfile>
            </activeProfiles>
        </settings>
