apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: lighthouse-hmac-token
    properties:
    - name: token
      question: Lighthouse webhook token
      help: The webhook token is used as a secret to verify webhooks come from a trusted
        source
      generator: hmac
  - name: lighthouse-oauth-token
    properties:
    - name: token
      question: Lighthouse webhook token
      help: The webhook token is used as a secret to verify webhooks come from a trusted
        source
      generator: gitOperator.password
  - name: knative-git-user-pass
    properties:
    - name: username
      key: secret/data/jx/pipelineUser
      question: the pipeline username
      help: the user name used by pipelines running in Jenkins X
      generator: gitOperator.username
    - name: token
      key: secret/data/jx/pipelineUser
      question: the pipeline token or password
      help: the token or password used by pipelines running in Jenkins X
      generator: gitOperator.password
  - name: jenkins-x-bucketrepo
    properties:
    - name: username
      question: bucket repository user name
      help: The username used to authenticate with the bucket repository
      defaultValue: admin
    - name: password
      question: bucket repository password
      help: The password to authenticate with the bucket repository
      minLength: 5
      maxLength: 41
      generator: password
  - name: jenkins-x-chartmuseum
    properties:
    - name: username
      question: chartmuseum repository user name
      help: The username used to authenticate with chartmuseum (the helm repository)
      defaultValue: admin
    - name: password
      question: chartmuseum repository password
      help: The password to authenticate with the chartmuseum (the helm repository)
      minLength: 5
      maxLength: 41
      generator: password
  - name: nexus
    properties:
    - name: username
      question: nexus user name
      help: The username used to authenticate with nexus
      defaultValue: admin
    - name: password
      question: nexus password
      help: The password to authenticate with nexus
      minLength: 5
      maxLength: 41
      defaultValue: admin123
  - name: knative-docker-user-pass
    properties:
    - name: password
      question: Docker Registry password
      help: The password used to access the external docker registry
      generator: password
