filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/jxboot-helmfile-resources
  version: 1.1.372
  name: jxboot-helmfile-resources
  values:
  - jxboot-helmfile-resources-values.yaml
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jenkins-x-crds
  version: 3.0.12
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jxgh/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-preview
  version: 0.5.1
  name: jx-preview
  values:
  - jx-values.yaml
- chart: jxgh/lighthouse
  version: 1.17.3
  name: lighthouse
  values:
  - ../../versionStream/charts/jxgh/lighthouse/values.yaml.gotmpl
  - jx-values.yaml
  - lighthouse-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.5.9
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/local-external-secrets
  version: 0.0.14
  name: local-external-secrets
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
